### ISSUE TITLE
how to open the .pk file?

### ISSUE THREAD

**Issue by chenryn** [QAZASDEDC/TopoMAD#3]
There are no .txt file described in the README, but .pk file. How can I open it?

**Comment by QAZASDEDC** [comment]
Sorry, we have updated the README file. Please refer to the new README.

**Comment by Coder-Liuu** [comment]
@chenryn 嗨，同学，你可以尝试通过下面的代码来打开.pk文件～

```python
with open("MBD_topology.pk","rb") as f:
    sensor_dist = pickle.load(f)
```
