### ISSUE TITLE
How to run ? 

### ISSUE THREAD

**Issue by JasonPeng1310** [QAZASDEDC/TopoMAD#6]
I want to know how to run this code, please how to run

**Comment by QAZASDEDC** [comment]
We also provided an example of running the code at [](https://github.com/QAZASDEDC/LinearList/blob/main/performance_evaluation_GAT-bias2false.ipynb). You can refer to it.

**Comment by QAZASDEDC** [comment]
We provided an example at https://github.com/QAZASDEDC/LinearList/blob/main/performance_evaluation_GAT-bias2false.ipynb. You can refer to it.

**Comment by JasonPeng1310** [comment]
谢谢！可以提供这些基准模型的代码嘛？ 七个基线异常检测器进行了比较，包括基于高斯的异常检测器，OC-SVM [21]，LOF [22]，简单的自动编码器 [23]，lstm-ad [8]，lstm-ed [9]，和RNN-EBM [10]

**Comment by QAZASDEDC** [comment]
可以参考sklearn和这个仓库：https://github.com/KDD-OpenSource/DeepADoTS
